"company_name","cantidad_pedidos"
"Wellington Importadora","2"
"Furia Bacalhau e Frutos do Mar","3"
"Lehmanns Marktstand","3"
"Rattlesnake Canyon Grocery","2"
"Que Delícia","2"
"Frankenversand","4"
"Around the Horn","4"
"Comércio Mineiro","2"
"Gourmet Lanchonetes","2"
"Victuailles en stock","2"
"Chop-suey Chinese","2"
"Alfreds Futterkiste","2"
"Lonesome Pine Restaurant","2"
"HILARION-Abastos","5"
"La corne d'abondance","2"
"Wolski  Zajazd","2"
"Blondesddsl père et fils","3"
"Die Wandernde Kuh","2"
"Ricardo Adocicados","3"
"La maison d'Asie","2"
"Bólido Comidas preparadas","2"
"Wartian Herkku","2"
"Bon app'","4"
"Eastern Connection","2"
"Suprêmes délices","4"
"Ernst Handel","5"
"LINO-Delicateses","2"
"Ottilies Käseladen","4"
"Tradição Hipermercados","2"
"Great Lakes Food Market","4"
"Save-a-lot Markets","4"
"Reggiani Caseifici","3"
"Maison Dewey","2"
"Queen Cozinha","2"
"Simons bistro","2"
"QUICK-Stop","5"
"Richter Supermarkt","2"
"Franchi S.p.A.","2"
"Folk och fä HB","2"
"Hanari Carnes","3"
"Rancho grande","2"
"Familia Arquibaldo","2"
"B's Beverages","2"
"Bottom-Dollar Markets","2"
"White Clover Markets","4"
"Romero y tomillo","3"
"Island Trading","4"
