version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: process.env.DB_USER
      POSTGRES_PASSWORD: process.env.DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql
  addressbook:
    build: 
      context: .
    environment:
      DB_SCHEMA: process.env.DB_SCHEMA
      DB_USER: process.env.DB_SCHEMA
      DB_PASSWORD: process.env.DB_PASSWORD
      DB_HOST: process.env.DB_HOST
      DB_PORT: process.env.DB_PORT
    depends_on:
      - postgres
    ports:
      - '9000:9000'
volumes:
  addressbook-db: