services:
  mysql:
    image: mysql:8.0
    container_name: payment_mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_db
    ports:
      - "3306:3306"
    volumes:
      - payment_mysql_data:/var/lib/mysql

volumes:
  payment_mysql_data: